### ISSUE TITLE
If you have the mod installed, but the locks are not enabled, despite having the permissions to use the locks, you cannot.

### ISSUE THREAD

**Issue by NeverNewer63** [FurryZoi/Devious-Obligate-Great-Stuff#1]
Let me explain with an example. My owner has this mod installed and she is my official BC owner. She has permission to use the locks. She tried to unlock the locks that were placed onto me by someone else the night before, and the mod crashed. When enabled the locks to be used on her, the mod no longer crashed.

This is undesirable as my owner does not want these locks to be used on her, but she does want to be able to free me from these locks. It would be excellent to have two switches of for anyone with this mod installed to be able to access the locks on others. Some doms do not want to these locks to be used on them, and that is understandable.

Additionally to better stop any trolls who would misuse the mod, it would be nice if the whitelist only permission setting for lock actually worked. At the current moment, it does not. If the locks are set to whitelist only in the permission menu, there is no effect on who can use them on you. Anyone still may use them on you.

**Comment by FurryZoi** [comment]
Ah, Sorry for the late response, I will push a fix tomorrow.
The devious padlock does not have permission system yet, BC's permission menu doesnt work with items from mods.
