### ISSUE TITLE
Message Spam Error

### ISSUE THREAD

**Issue by NeverNewer63** [FurryZoi/Devious-Obligate-Great-Stuff#3]
Somehow the lock was repeatedly being removed and reapplied from a chastity belt on someone, which I have heard the belts now no longer work with all locks due to a bug or something, and this spammed the chat with hundreds of messages. Please put a limit on how many messages can be sent within a short time or find some way to limit the disruption to others in scenarios like this one.

**Comment by FurryZoi** [comment]
I do not know what this problem is related to, one thing I know for sure, it happens with certain items that were used in R110.
I have set a limit so that devious padlocks stop working in case of spam...

**Comment by FurryZoi** [comment]
Damn.... I fixed it using validation.
